"""
Trading Agents CLI.

Usage:
  python main.py <ticker> <date>                    # Run all 4 analysts in parallel
  python main.py <ticker> <date> --agent technical  # Run a single agent
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path
from typing import List

from agents.schemas import AnalystReport
from harness.orchestrator import run_analyst_team, consensus_signal

_SINGLE_AGENT_MAP = {
    "technical": None,
    "fundamental": None,
    "sentiment": None,
    "macro_policy": None,
}


def _load_single_agent(name: str):
    if name == "technical":
        from agents.technical import run_technical_analysis
        return run_technical_analysis
    if name == "fundamental":
        from agents.fundamental import run_fundamental_analysis
        return run_fundamental_analysis
    if name == "sentiment":
        from agents.sentiment import run_sentiment_analysis
        return run_sentiment_analysis
    if name == "macro_policy":
        from agents.macro_policy import run_macro_analysis
        return run_macro_analysis
    raise ValueError(f"Unknown agent: {name}")


_SIGNAL_ICON = {"bullish": "▲", "bearish": "▼", "neutral": "◆"}


def _render_report(ticker: str, date: str, reports: List[AnalystReport]) -> str:
    signal, avg_conf = consensus_signal(reports)
    icon = _SIGNAL_ICON[signal]

    sections = [f"# Trading Analysis: {ticker}  ({date})\n"]
    sections.append(f"## Consensus: {icon} {signal.upper()}  (avg confidence: {avg_conf:.0%})\n")

    # Per-agent summaries
    sections.append("## Analyst Reports\n")
    for r in reports:
        agent_icon = _SIGNAL_ICON.get(r.signal, "◆")
        sections.append(f"### {r.agent.replace('_', ' ').title()}  {agent_icon} {r.signal.upper()} ({r.confidence:.0%})")
        sections.append(r.summary)
        sections.append("**Key factors:**")
        sections.extend(f"- {f}" for f in r.key_factors)
        sections.append("**Risks:**")
        sections.extend(f"- {f}" for f in r.risks)
        sections.append("")

    sections.append("---")
    sections.append("*Generated by trading-agents — for informational purposes only, not financial advice.*")

    return "\n".join(sections)


async def analyze(ticker: str, date: str, agent: str | None = None) -> None:
    if agent:
        print(f"Running {agent} agent for {ticker} as of {date}...")
        run_fn = _load_single_agent(agent)
        report = await run_fn(ticker, date)
        reports = [report]
    else:
        print(f"Running 4 analyst agents in parallel for {ticker} as of {date}...")
        reports = await run_analyst_team(ticker, date)
        print(f"All agents complete.")

    output = _render_report(ticker, date, reports)
    print("\n" + output)

    output_dir = Path.home() / ".trading-agents" / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    tag = f"_{agent}" if agent else ""
    filename = output_dir / f"{ticker.replace('.', '_')}_{date.replace('-', '')}{tag}.md"
    filename.write_text(output, encoding="utf-8")
    print(f"\nReport saved: {filename}")


def main() -> None:
    if len(sys.argv) < 3:
        print("Usage: python main.py <ticker> <date> [--agent technical|fundamental|sentiment|macro_policy]")
        print("Examples:")
        print("  python main.py AAPL 2024-05-10")
        print("  python main.py 600519 2024-05-10")
        print("  python main.py AAPL 2024-05-10 --agent technical")
        sys.exit(1)

    ticker = sys.argv[1]
    date = sys.argv[2]
    agent = None

    if "--agent" in sys.argv:
        idx = sys.argv.index("--agent")
        if idx + 1 < len(sys.argv):
            agent = sys.argv[idx + 1]

    asyncio.run(analyze(ticker, date, agent))


if __name__ == "__main__":
    main()
