"""
Trading Agents CLI — Phase 1: single technical analysis agent.
"""

import asyncio
import sys
from pathlib import Path

from agents.technical import run_technical_analysis


def _render_report(ticker: str, date: str, report) -> str:
    signals_emoji = {"bullish": "▲", "bearish": "▼", "neutral": "◆"}
    icon = signals_emoji.get(report.signal, "◆")
    return f"""# Technical Analysis: {ticker} ({date})

**Signal:** {icon} {report.signal.upper()}
**Confidence:** {report.confidence:.0%}

## Key Factors
{chr(10).join(f"- {f}" for f in report.key_factors)}

## Risks
{chr(10).join(f"- {r}" for r in report.risks)}

## Summary
{report.summary}

---
*Generated by trading-agents (technical agent)*
"""


async def analyze(ticker: str, date: str) -> None:
    print(f"Analyzing {ticker} as of {date}...")

    report = await run_technical_analysis(ticker, date)
    output = _render_report(ticker, date, report)

    print("\n" + output)

    output_dir = Path.home() / ".trading-agents" / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    filename = output_dir / f"{ticker.replace('.', '_')}_{date.replace('-', '')}.md"
    filename.write_text(output, encoding="utf-8")
    print(f"Report saved: {filename}")


def main() -> None:
    if len(sys.argv) < 3:
        print("Usage: python main.py <ticker> <date>")
        print("Examples:")
        print("  python main.py AAPL 2024-05-10")
        print("  python main.py 600519 2024-05-10")
        print("  python main.py 0700.HK 2024-05-10")
        sys.exit(1)

    ticker = sys.argv[1]
    date = sys.argv[2]
    asyncio.run(analyze(ticker, date))


if __name__ == "__main__":
    main()
